force-app/main/default/objects/Users__c/Users__c.object-meta.xml
<CustomObject>
    <label>Users</label>
    <nameField>
        <label>users Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Users__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserManagerREST.cls
@RestResource(urlMapping='/Users__c/*')
global with sharing class UserManagerREST {
    public UserManagerREST() {
    }

    global class RequestBody {
        public String name;
        public String email;
    }

    @HttpPost
    global static String Create(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        RequestBody requestBody = (RequestBody) JSON.deserialize(req.requestBody.toString(), RequestBody.class);
        try {
            Users__c u = new Users__c();
            u.email__c = requestBody.email;
            u.name__c = requestBody.name;
            insert u;
            
            return u.Id;
        } catch (Exception err) {
            return 'email: ' + requestBody.email + 'name: ' + requestBody.name + ' err: ' + err.getMessage();
        }
    }
}