force-app/main/default/objects/Users__c/Users__c.object-meta.xml
<CustomObject>
    <label>Users</label>
    <nameField>
        <label>users Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Users__c/fields/name__c.field-meta.xml
<CustomField>
    <fullName>name__c</fullName>
    <label>name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UserManager.cls
global with sharing class UserManager {
    public UserManager() {
    }
    // public static String Create(String name, String email){
    //     try {
    //         if (email == null || email == '') {
    //             throw new AuraHandledException('Email is required');
    //         }
    //         Users__c  u = new Users__c();
    //         u.name__c = name;
    //         u.email__c = email;
    //         insert u;
    //         return u.Id;
    //     } catch (Exception err) {
    //         return err.getMessage();
    //     }
    // }
    @AuraEnabled(cacheable=true)
    public static  List<Users__c> GetAll() {
        try {
            List<Users__c> userList = [SELECT Id, name__c, email__c FROM Users__c];
            return userList;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}